### ISSUE TITLE
JIZ r0, <location> takes 8 ticks after assigning to r0

### ISSUE THREAD

**Issue by jchilibe** [Labdabeta/vns#30]
After performing a command that sets r0 (ie. wlk E, r0, r0), the command jiz r0, location takes 8 uT instead of 1. Branch predictor upgrades don't impact this.

**Comment by Cluedrew** [comment]
I think there is a more general problem relating to registers not updating in time. I haven't been able to replicate it in the small scale yet, but I have issues all of a sudden with garbage values getting loaded into various registers. It usually seems to happen around branches. In one case I got 2 different values (20, 10) in r0 in the same ut.

I think you might want to reconsider your main loop, and the "pseudo loop" of unit command execution, it seems to be a lot more error prone than it should be. (Or course I don't know what is actually wrong, my guess may be way off.)

**Comment by Labdabeta** [comment]
There is indeed a problem with register update time going on. The reason for the unorthodox main loop is that unlike a real CPU (where I can just do a simple fetch-execute-writeback loop) the vns processors can actually do certain operations in exactly 0 time. Thus the loops have to be nested and it is easy to miss a register update. This issue will be fixed by a push shortly.
